sonar.projectKey=OttScott_distract-me-not
sonar.organization=ottscott

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=distract-me-not
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx

# Encoding of the source code. Default is default system encoding
sonar.sourceEncoding=UTF-8

# JavaScript/TypeScript specific settings
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.testExecutionReportPaths=test-report.xml

# Exclude files from analysis
sonar.exclusions=**/node_modules/**,**/build/**,**/public/**,**/*.test.js,**/*.test.jsx,**/*.spec.js,**/*.spec.jsx,**/coverage/**
